package com.mycompany.vittostore.generalitems;


public enum PromotionBreakfast {
    CAFE_2_MEDIALUNAS,
    CAFE_TORTA_INDIVIDUAL,
    CAFE_TOSTADO_ARABE,
    CAFE_CUADRADO_DULCE,
    CAFE_GALLETAS_CHOCO,
    CAPPUCCINO_TOSTADAS,
    CAPPUCCINO_MEDIALUNAS,
    NARANJA_MEDIALUNAS,
    NARANJA_TOSTADOS,
    LICUADO_medio_TOSTADO,
    LIMONADA_TORTA_IND,
    ALFAJOR_MAICENA_CHOCO,
    MILKSHAKES_TORTA_IND,
    LICUADOS_2_1_TOSTADO,
    COPA_YOGURT,
    TOSTADAS_EXP_ESP,
    FRUTA_CAFE_TOSTADO,
    ICE_CAPPUCCINO
}
