 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vittostore;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.*;
import java.awt.event.WindowEvent;


import com.mycompany.vittostore.generalitems.Product;
import com.mycompany.vittostore.generalitems.Table;
import com.mycompany.vittostore.generalitems.NoAlcoholDrinksEnum;
import com.mycompany.vittostore.database.VittoStoreDDBBRepository;
import com.mycompany.vittostore.user.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerNumberModel;


public class VittoFrame extends javax.swing.JFrame {
    
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    List<User> employeeList = new ArrayList<>();
    List<Product> productList = new ArrayList<>();
    Table selectedTable = new Table();
    VittoStoreDDBBRepository vittoDDBBStore = null;
    Map<NoAlcoholDrinksEnum, Integer> noAlcoholDrinks;
    Map<NoAlcoholDrinksEnum, Integer> AlcoholDrinks;
    User tableUser;
    // resto de las posibilidades por mesa
    
        

    /**
     * Creates new form VittoFrame
     * 
     * sout -> System.out.println(); -> shortCut
     */
    public VittoFrame() {    
        initComponents();
        
        try {
            vittoDDBBStore = new VittoStoreDDBBRepository();
            this.employeeList = vittoDDBBStore.getUsers();
            
        } catch (SQLException ex) {
            Logger.getLogger(VittoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    
    
    private void chargeEmployee() {
        List<String> employeeNamesList = new ArrayList<>();
        this.employeeList.forEach( t -> 
                employeeNamesList.add(t.getNombre() + " " + t.getApellido())
                
        );
        
        DefaultComboBoxModel employeeModel = new DefaultComboBoxModel(employeeNamesList.toArray());
        this.employeeNameCombo.setModel(employeeModel);        
        
    }
    
    
    
    private void selectOrderView(int table) {
        SelectOrder.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        SelectOrder.setSize(700, 500);        
        SelectOrder.setVisible(true);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectOrder = new javax.swing.JFrame();
        employeeNameCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        drinkNoAlcohol = new javax.swing.JButton();
        drinkAlcohol = new javax.swing.JButton();
        candyProducts = new javax.swing.JButton();
        saladProducts = new javax.swing.JButton();
        promotions = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        consuming = new javax.swing.JButton();
        payAction = new javax.swing.JButton();
        seeConsuming = new javax.swing.JButton();
        deleteTable = new javax.swing.JButton();
        closeTable = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        DrinkNoAlcoholFrame = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        acceptNoAlcoholDrinks = new javax.swing.JButton();
        cancelNoAlcoholDrinks = new javax.swing.JButton();
        cocaColaCheck = new javax.swing.JCheckBox();
        cocaSpinner = new javax.swing.JSpinner();
        cocaLightCheck = new javax.swing.JCheckBox();
        cocaLightSpinner = new javax.swing.JSpinner();
        spriteCheck = new javax.swing.JCheckBox();
        spriteSpinner = new javax.swing.JSpinner();
        spriteZeroCheck = new javax.swing.JCheckBox();
        spriteZeroSpinner = new javax.swing.JSpinner();
        tonicaCheck = new javax.swing.JCheckBox();
        torosTonicaSpinner = new javax.swing.JSpinner();
        fantaCheck = new javax.swing.JCheckBox();
        fantaSpinner = new javax.swing.JSpinner();
        naranjaCheck = new javax.swing.JCheckBox();
        naranjaSpinner = new javax.swing.JSpinner();
        pomeloCheck = new javax.swing.JCheckBox();
        pomeloSpinner = new javax.swing.JSpinner();
        manzanaCheck = new javax.swing.JCheckBox();
        manzanaSpinner = new javax.swing.JSpinner();
        limonadaCheck = new javax.swing.JCheckBox();
        limonadaSpinner = new javax.swing.JSpinner();
        pomeloTorosCheck = new javax.swing.JCheckBox();
        torosPomeloSpinner = new javax.swing.JSpinner();
        waterCheck = new javax.swing.JCheckBox();
        waterSpinner = new javax.swing.JSpinner();
        waterGasCheck = new javax.swing.JCheckBox();
        waterGasSpinner = new javax.swing.JSpinner();
        exprimidoCheck = new javax.swing.JCheckBox();
        exprimidoSpinner = new javax.swing.JSpinner();
        limonadaElaboradoCheck = new javax.swing.JCheckBox();
        limonada_elaborada_Spinner = new javax.swing.JSpinner();
        licuadoLecheCheck = new javax.swing.JCheckBox();
        licuadoAguaCheck = new javax.swing.JCheckBox();
        licuadoLecheSpinner = new javax.swing.JSpinner();
        licuadoAguaSpinner = new javax.swing.JSpinner();
        shakeDulceLecheCheck = new javax.swing.JCheckBox();
        shakeDulceLecheSpinner = new javax.swing.JSpinner();
        shakeChocolateCheck = new javax.swing.JCheckBox();
        shakeChocolateSpinner = new javax.swing.JSpinner();
        cepitaCheck = new javax.swing.JCheckBox();
        cepitaSpinner = new javax.swing.JSpinner();
        scheweppesPomeloCheck = new javax.swing.JCheckBox();
        scheweppesTonicaCheck = new javax.swing.JCheckBox();
        scheweppesPomeloSpinner = new javax.swing.JSpinner();
        scheweppesTonicaSpinner = new javax.swing.JSpinner();
        DrinkAlcoholFrame = new javax.swing.JFrame();
        CandyProductsFrame = new javax.swing.JFrame();
        SaladsProductFrame = new javax.swing.JFrame();
        SuggestedPromosFrame = new javax.swing.JFrame();
        tableOne = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tableTwo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tableThree = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tableFour = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        employeeNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNameComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Quién sos ?");

        drinkNoAlcohol.setText("Bebidas sin alcohol");
        drinkNoAlcohol.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                drinkNoAlcoholAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        drinkNoAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkNoAlcoholActionPerformed(evt);
            }
        });

        drinkAlcohol.setText("Bebidas con alcohol");
        drinkAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkAlcoholActionPerformed(evt);
            }
        });

        candyProducts.setText("Productos Dulces");
        candyProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candyProductsActionPerformed(evt);
            }
        });

        saladProducts.setText("Productos Salados");
        saladProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladProductsActionPerformed(evt);
            }
        });

        promotions.setText("Promos Sugeridas");
        promotions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promotionsActionPerformed(evt);
            }
        });

        consuming.setText("Consumiendo");
        consuming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumingActionPerformed(evt);
            }
        });

        payAction.setText("Pagar");
        payAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionActionPerformed(evt);
            }
        });

        seeConsuming.setText("Ver Consumo");
        seeConsuming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeConsumingActionPerformed(evt);
            }
        });

        deleteTable.setText("Eliminar");
        deleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTableActionPerformed(evt);
            }
        });

        closeTable.setText("Cerrar Mesa");
        closeTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTableActionPerformed(evt);
            }
        });

        SaveButton.setText("Guardar");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectOrderLayout = new javax.swing.GroupLayout(SelectOrder.getContentPane());
        SelectOrder.getContentPane().setLayout(SelectOrderLayout);
        SelectOrderLayout.setHorizontalGroup(
            SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(SelectOrderLayout.createSequentialGroup()
                .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectOrderLayout.createSequentialGroup()
                        .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectOrderLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(drinkAlcohol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(drinkNoAlcohol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(candyProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saladProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(promotions, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SelectOrderLayout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(jLabel4)))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(SelectOrderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SelectOrderLayout.createSequentialGroup()
                                .addComponent(consuming)
                                .addGap(18, 18, 18)
                                .addComponent(payAction, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(closeTable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seeConsuming, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(deleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectOrderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(employeeNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        SelectOrderLayout.setVerticalGroup(
            SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectOrderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(promotions, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(candyProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drinkNoAlcohol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(drinkAlcohol, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(saladProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consuming)
                    .addComponent(payAction)
                    .addComponent(seeConsuming)
                    .addComponent(deleteTable))
                .addGap(39, 39, 39)
                .addGroup(SelectOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SaveButton))
                .addGap(74, 74, 74))
        );

        jLabel6.setText("Línea Gaseosas");

        jLabel7.setText("Línea Elaborados");

        acceptNoAlcoholDrinks.setText("Aceptar");
        acceptNoAlcoholDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptNoAlcoholDrinksActionPerformed(evt);
            }
        });

        cancelNoAlcoholDrinks.setText("Cancelar");
        cancelNoAlcoholDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNoAlcoholDrinksActionPerformed(evt);
            }
        });

        cocaColaCheck.setText("coca cola");
        cocaColaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaColaCheckActionPerformed(evt);
            }
        });

        cocaLightCheck.setText("coca light");
        cocaLightCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaLightCheckActionPerformed(evt);
            }
        });

        spriteCheck.setText("sprite");
        spriteCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteCheckActionPerformed(evt);
            }
        });

        spriteZeroCheck.setText("sprite zero");
        spriteZeroCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteZeroCheckActionPerformed(evt);
            }
        });

        tonicaCheck.setText("toros tónica");
        tonicaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tonicaCheckActionPerformed(evt);
            }
        });

        fantaCheck.setText("fanta");
        fantaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaCheckActionPerformed(evt);
            }
        });

        naranjaCheck.setText("levite naranja");
        naranjaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naranjaCheckActionPerformed(evt);
            }
        });

        pomeloCheck.setText("levite pomelo");
        pomeloCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomeloCheckActionPerformed(evt);
            }
        });

        manzanaCheck.setText("levite manzana");
        manzanaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manzanaCheckActionPerformed(evt);
            }
        });

        limonadaCheck.setText("levite limonada");
        limonadaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limonadaCheckActionPerformed(evt);
            }
        });

        pomeloTorosCheck.setText("toros pomelo");
        pomeloTorosCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomeloTorosCheckActionPerformed(evt);
            }
        });

        waterCheck.setText("agua");
        waterCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterCheckActionPerformed(evt);
            }
        });

        waterGasCheck.setText("agua c/gas");
        waterGasCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterGasCheckActionPerformed(evt);
            }
        });

        exprimidoCheck.setText("exprimido");
        exprimidoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exprimidoCheckActionPerformed(evt);
            }
        });

        limonadaElaboradoCheck.setText("limonada");
        limonadaElaboradoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limonadaElaboradoCheckActionPerformed(evt);
            }
        });

        licuadoLecheCheck.setText("licuado c/ leche");
        licuadoLecheCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licuadoLecheCheckActionPerformed(evt);
            }
        });

        licuadoAguaCheck.setText("licuado c/ agua");
        licuadoAguaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licuadoAguaCheckActionPerformed(evt);
            }
        });

        shakeDulceLecheCheck.setText("Milk Shake (dulce de leche)");
        shakeDulceLecheCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shakeDulceLecheCheckActionPerformed(evt);
            }
        });

        shakeChocolateCheck.setText("Milk Shake (chocolate)");
        shakeChocolateCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shakeChocolateCheckActionPerformed(evt);
            }
        });

        cepitaCheck.setText("cepita");
        cepitaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepitaCheckActionPerformed(evt);
            }
        });

        scheweppesPomeloCheck.setText("scheweppes pomelo");
        scheweppesPomeloCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheweppesPomeloCheckActionPerformed(evt);
            }
        });

        scheweppesTonicaCheck.setText("scheweppes tonica");
        scheweppesTonicaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheweppesTonicaCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DrinkNoAlcoholFrameLayout = new javax.swing.GroupLayout(DrinkNoAlcoholFrame.getContentPane());
        DrinkNoAlcoholFrame.getContentPane().setLayout(DrinkNoAlcoholFrameLayout);
        DrinkNoAlcoholFrameLayout.setHorizontalGroup(
            DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2))
                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                .addComponent(shakeChocolateCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shakeChocolateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                .addComponent(shakeDulceLecheCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(shakeDulceLecheSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator3))
                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(spriteCheck)
                                                    .addComponent(cocaLightCheck)
                                                    .addComponent(cocaColaCheck))
                                                .addGap(37, 37, 37)
                                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cocaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cocaLightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(spriteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(spriteZeroCheck)
                                                    .addComponent(tonicaCheck))
                                                .addGap(21, 21, 21)
                                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(torosTonicaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(spriteZeroSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(torosPomeloSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fantaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(fantaCheck)
                                            .addComponent(pomeloTorosCheck))
                                        .addGap(55, 55, 55)
                                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pomeloCheck)
                                                    .addComponent(naranjaCheck))
                                                .addGap(18, 18, 18)
                                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(naranjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pomeloSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                                .addComponent(manzanaCheck)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(manzanaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(limonadaCheck)
                                                    .addComponent(waterCheck)
                                                    .addComponent(cepitaCheck)
                                                    .addComponent(waterGasCheck))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cepitaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(waterGasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(waterSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(limonadaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(exprimidoCheck)
                                            .addComponent(limonadaElaboradoCheck))
                                        .addGap(18, 18, 18)
                                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(limonada_elaborada_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(exprimidoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(cancelNoAlcoholDrinks)
                                                .addGap(41, 41, 41)
                                                .addComponent(acceptNoAlcoholDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                                        .addComponent(licuadoAguaCheck)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(licuadoAguaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                                        .addComponent(licuadoLecheCheck)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(licuadoLecheSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(scheweppesPomeloCheck)
                                            .addComponent(scheweppesTonicaCheck))
                                        .addGap(18, 18, 18)
                                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(scheweppesTonicaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scheweppesPomeloSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        DrinkNoAlcoholFrameLayout.setVerticalGroup(
            DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cocaColaCheck)
                            .addComponent(cocaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cocaLightCheck)
                            .addComponent(cocaLightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(naranjaCheck)
                            .addComponent(naranjaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pomeloCheck)
                            .addComponent(pomeloSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spriteCheck)
                    .addComponent(spriteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manzanaCheck)
                    .addComponent(manzanaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spriteZeroCheck)
                    .addComponent(spriteZeroSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limonadaCheck)
                    .addComponent(limonadaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tonicaCheck)
                    .addComponent(torosTonicaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepitaCheck)
                    .addComponent(cepitaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pomeloTorosCheck)
                    .addComponent(torosPomeloSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterCheck)
                    .addComponent(waterSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fantaCheck)
                    .addComponent(fantaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterGasCheck)
                    .addComponent(waterGasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                        .addGap(3, 91, Short.MAX_VALUE)
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(exprimidoCheck)
                                    .addComponent(exprimidoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(limonadaElaboradoCheck)
                                    .addComponent(limonada_elaborada_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DrinkNoAlcoholFrameLayout.createSequentialGroup()
                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(licuadoLecheCheck)
                                    .addComponent(licuadoLecheSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(licuadoAguaCheck)
                                    .addComponent(licuadoAguaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shakeDulceLecheSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shakeDulceLecheCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shakeChocolateCheck)
                            .addComponent(shakeChocolateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelNoAlcoholDrinks)
                            .addComponent(acceptNoAlcoholDrinks))
                        .addContainerGap())
                    .addGroup(DrinkNoAlcoholFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scheweppesPomeloSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scheweppesPomeloCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DrinkNoAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scheweppesTonicaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scheweppesTonicaCheck))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout DrinkAlcoholFrameLayout = new javax.swing.GroupLayout(DrinkAlcoholFrame.getContentPane());
        DrinkAlcoholFrame.getContentPane().setLayout(DrinkAlcoholFrameLayout);
        DrinkAlcoholFrameLayout.setHorizontalGroup(
            DrinkAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        DrinkAlcoholFrameLayout.setVerticalGroup(
            DrinkAlcoholFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CandyProductsFrameLayout = new javax.swing.GroupLayout(CandyProductsFrame.getContentPane());
        CandyProductsFrame.getContentPane().setLayout(CandyProductsFrameLayout);
        CandyProductsFrameLayout.setHorizontalGroup(
            CandyProductsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        CandyProductsFrameLayout.setVerticalGroup(
            CandyProductsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SaladsProductFrameLayout = new javax.swing.GroupLayout(SaladsProductFrame.getContentPane());
        SaladsProductFrame.getContentPane().setLayout(SaladsProductFrameLayout);
        SaladsProductFrameLayout.setHorizontalGroup(
            SaladsProductFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        SaladsProductFrameLayout.setVerticalGroup(
            SaladsProductFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SuggestedPromosFrameLayout = new javax.swing.GroupLayout(SuggestedPromosFrame.getContentPane());
        SuggestedPromosFrame.getContentPane().setLayout(SuggestedPromosFrameLayout);
        SuggestedPromosFrameLayout.setHorizontalGroup(
            SuggestedPromosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        SuggestedPromosFrameLayout.setVerticalGroup(
            SuggestedPromosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableOne.setBackground(new java.awt.Color(51, 204, 0));
        tableOne.setText("1");
        tableOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableOneActionPerformed(evt);
            }
        });

        jLabel1.setText("Mesa");

        tableTwo.setBackground(new java.awt.Color(51, 204, 0));
        tableTwo.setText("2");
        tableTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableTwoActionPerformed(evt);
            }
        });

        jLabel2.setText("Mesa");

        tableThree.setBackground(new java.awt.Color(51, 204, 0));
        tableThree.setText("3");
        tableThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableThreeActionPerformed(evt);
            }
        });

        jLabel3.setText("Mesa");

        tableFour.setBackground(new java.awt.Color(51, 204, 0));
        tableFour.setText("4");
        tableFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableFourActionPerformed(evt);
            }
        });

        jLabel5.setText("Mesa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableOne, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tableThree, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tableFour, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tableTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tableThree, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableOne, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tableFour, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(703, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableOneActionPerformed
        // TODO add your handling code here:
        
        System.out.println("click...");
        System.out.println(evt);        
        
        this.selectedTable.setState("trableOne");
        this.tableOne.setBackground(Color.red);
        this.chargeEmployee(); 
        this.selectOrderView(1);
    
    }//GEN-LAST:event_tableOneActionPerformed

    private void employeeNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNameComboActionPerformed
        
                
        String [] names = this.employeeNameCombo.getSelectedItem().toString().split(" ");
        System.out.println(names[0] + names[1]);
        
        this.tableUser = this.vittoDDBBStore.findUserByCompleteName(names[0], names[1]);        
        
    }//GEN-LAST:event_employeeNameComboActionPerformed

    private void tableTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableTwoActionPerformed
        // TODO add your handling code here:
        this.selectedTable.setState("TableTwo");
        this.tableOne.setBackground(Color.red);
        this.chargeEmployee(); 
        this.selectOrderView(2);

    }//GEN-LAST:event_tableTwoActionPerformed

    private void tableThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableThreeActionPerformed
        // TODO add your handling code here:
        this.selectedTable.setState("TableThree");
        this.tableOne.setBackground(Color.red);
        this.chargeEmployee(); 
        this.selectOrderView(3);

    }//GEN-LAST:event_tableThreeActionPerformed

    private void drinkNoAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkNoAlcoholActionPerformed
        
        DrinkNoAlcoholFrame.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        DrinkNoAlcoholFrame.setSize(550, 700);
        DrinkNoAlcoholFrame.setVisible(true);     
        
        System.out.println("Table selected.......");
        System.out.println(this.selectedTable.getState());
        

        /*
            Buscar de la base de datos, si hay algo que ya se había pedido 
            para esa mesa
        
        */
        
        if(false) {
            // no se encontraron datos en la bbdd
            // por lo tanto hay que cargar las cantidades que se 
            // hayan guardado
        } else {
            // no hay datos entoences se tiene que guardar los datos elegidos.
        cocaSpinner.setEnabled(false);
        cocaLightSpinner.setEnabled(false);
        spriteSpinner.setEnabled(false);
        spriteZeroSpinner.setEnabled(false);
        torosPomeloSpinner.setEnabled(false);
        torosTonicaSpinner.setEnabled(false);
        fantaSpinner.setEnabled(false);
        naranjaSpinner.setEnabled(false);
        pomeloSpinner.setEnabled(false);
        manzanaSpinner.setEnabled(false);
        limonadaSpinner.setEnabled(false);
        cepitaSpinner.setEnabled(false);
        scheweppesPomeloSpinner.setEnabled(false);
        scheweppesTonicaSpinner.setEnabled(false);
        waterSpinner.setEnabled(false);
        waterGasSpinner.setEnabled(false);
        exprimidoSpinner.setEnabled(false);
        licuadoAguaSpinner.setEnabled(false);
        licuadoLecheSpinner.setEnabled(false);
        limonada_elaborada_Spinner.setEnabled(false);
        shakeChocolateSpinner.setEnabled(false);
        shakeDulceLecheSpinner.setEnabled(false);
            
        }
        
        
    }//GEN-LAST:event_drinkNoAlcoholActionPerformed

    private void candyProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candyProductsActionPerformed
        
        CandyProductsFrame.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        CandyProductsFrame.setSize(650, 700);
        CandyProductsFrame.setVisible(true);  
        
    }//GEN-LAST:event_candyProductsActionPerformed

    private void promotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promotionsActionPerformed
        // TODO add your handling code here:
        SuggestedPromosFrame.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        SuggestedPromosFrame.setSize(650, 700);
        SuggestedPromosFrame.setVisible(true);  
        
    }//GEN-LAST:event_promotionsActionPerformed

    private void saladProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladProductsActionPerformed
        // TODO add your handling code here:
        SaladsProductFrame.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        SaladsProductFrame.setSize(650, 700);
        SaladsProductFrame.setVisible(true);  
    }//GEN-LAST:event_saladProductsActionPerformed

    private void drinkAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkAlcoholActionPerformed
        // TODO add your handling code here:
        DrinkAlcoholFrame.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        DrinkAlcoholFrame.setSize(650, 700);
        DrinkAlcoholFrame.setVisible(true);
        
    }//GEN-LAST:event_drinkAlcoholActionPerformed

    private void consumingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumingActionPerformed

    private void seeConsumingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeConsumingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seeConsumingActionPerformed

    private void closeTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeTableActionPerformed

    private void deleteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTableActionPerformed

    private void payActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payActionActionPerformed

    private void tableFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableFourActionPerformed
        // TODO add your handling code here:
        this.selectedTable.setState("TableFour");
        this.tableOne.setBackground(Color.red);
        this.chargeEmployee(); 
        this.selectOrderView(4);

    }//GEN-LAST:event_tableFourActionPerformed

    private void drinkNoAlcoholAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_drinkNoAlcoholAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_drinkNoAlcoholAncestorAdded

    private void scheweppesTonicaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheweppesTonicaCheckActionPerformed
        if(scheweppesTonicaCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.scheweppesTonicaSpinner.setEnabled(true);
            this.scheweppesTonicaSpinner.setModel(model);
        } else {
            this.scheweppesTonicaSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_scheweppesTonicaCheckActionPerformed

    private void shakeDulceLecheCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shakeDulceLecheCheckActionPerformed
        if(shakeDulceLecheCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.shakeDulceLecheSpinner.setEnabled(true);
            this.shakeDulceLecheSpinner.setModel(model);
        } else {
            this.shakeDulceLecheSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_shakeDulceLecheCheckActionPerformed

    private void exprimidoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exprimidoCheckActionPerformed
        if(exprimidoCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.exprimidoSpinner.setEnabled(true);
            this.exprimidoSpinner.setModel(model);
        } else {
            this.exprimidoSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_exprimidoCheckActionPerformed

    private void manzanaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manzanaCheckActionPerformed
        if(manzanaCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.manzanaSpinner.setEnabled(true);
            this.manzanaSpinner.setModel(model);
        } else {
            this.manzanaSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_manzanaCheckActionPerformed

    private void pomeloCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomeloCheckActionPerformed
        if(pomeloCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.pomeloSpinner.setEnabled(true);
            this.pomeloSpinner.setModel(model);
        } else {
            this.pomeloSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_pomeloCheckActionPerformed

    private void naranjaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naranjaCheckActionPerformed
        if(naranjaCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.naranjaSpinner.setEnabled(true);
            this.naranjaSpinner.setModel(model);
        } else {
            this.naranjaSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_naranjaCheckActionPerformed

    private void fantaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaCheckActionPerformed
        if(fantaCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.fantaSpinner.setEnabled(true);
            this.fantaSpinner.setModel(model);
        } else {
            this.fantaSpinner.setEnabled(false);
        }
        
    }//GEN-LAST:event_fantaCheckActionPerformed

    private void tonicaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tonicaCheckActionPerformed
        if(tonicaCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.torosTonicaSpinner.setEnabled(true);
            this.torosTonicaSpinner.setModel(model);
        } else {
            this.torosTonicaSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_tonicaCheckActionPerformed

    private void spriteZeroCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteZeroCheckActionPerformed
        // TODO add your handling code here:
        if(spriteZeroCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.spriteZeroSpinner.setEnabled(true);
            this.spriteZeroSpinner.setModel(model);
        } else {
            this.spriteZeroSpinner.setEnabled(false);
        }        
    }//GEN-LAST:event_spriteZeroCheckActionPerformed

    private void spriteCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteCheckActionPerformed
        if(spriteCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.spriteSpinner.setEnabled(true);
            this.spriteSpinner.setModel(model);
        } else {
            this.spriteSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_spriteCheckActionPerformed

    private void cocaLightCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaLightCheckActionPerformed
        if(cocaLightCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.cocaLightSpinner.setEnabled(true);
            this.cocaLightSpinner.setModel(model);
        } else {
            this.cocaLightSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_cocaLightCheckActionPerformed

    private void cocaColaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaColaCheckActionPerformed
        // TODO add your handling code here:

        if(cocaColaCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.cocaSpinner.setEnabled(true);
            this.cocaSpinner.setModel(model);
        } else {
            this.cocaSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_cocaColaCheckActionPerformed

    private void cancelNoAlcoholDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNoAlcoholDrinksActionPerformed
        // TODO add your handling code here:

        /*
        Vaciar todos los contadores
        No modificar el estado de la cuenta
        */
        
        this.DrinkNoAlcoholFrame.dispatchEvent(new WindowEvent(this.DrinkNoAlcoholFrame, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancelNoAlcoholDrinksActionPerformed

    private void acceptNoAlcoholDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptNoAlcoholDrinksActionPerformed
        // TODO add your handling code here:

        /*
        Contabilizar todos los productos que se cargan
        Cambiar el estado de la mesa
        Guardarlos en la bbdd
        */

        this.noAlcoholDrinks = new HashMap();

        if(cocaColaCheck.isSelected() && Integer.parseInt(this.cocaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.COCA_COLA), Integer.parseInt(this.cocaSpinner.getValue().toString()));
        }

        if(cocaLightCheck.isSelected() && Integer.parseInt(this.cocaLightSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.COCA_LIGHT), Integer.parseInt(this.cocaLightSpinner.getValue().toString()));
        }

        if(spriteCheck.isSelected() && Integer.parseInt(this.spriteSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.SPRITE), Integer.parseInt(this.spriteSpinner.getValue().toString()));
        }

        if(spriteZeroCheck.isSelected() && Integer.parseInt(this.spriteZeroSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.SPRITE_ZERO), Integer.parseInt(this.spriteZeroSpinner.getValue().toString()));
        }

        if(tonicaCheck.isSelected() && Integer.parseInt(this.torosTonicaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.PASO_TOROS_TONICA), Integer.parseInt(this.torosTonicaSpinner.getValue().toString()));
        }

        if(pomeloTorosCheck.isSelected() && Integer.parseInt(this.torosPomeloSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.PASO_TOROS_POMELO), Integer.parseInt(this.torosPomeloSpinner.getValue().toString()));
        }

        if(fantaCheck.isSelected() && Integer.parseInt(this.fantaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.FANTA), Integer.parseInt(this.fantaSpinner.getValue().toString()));
        }

        if(naranjaCheck.isSelected() && Integer.parseInt(this.naranjaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.LEVITE_NARANJA), Integer.parseInt(this.naranjaSpinner.getValue().toString()));
        }

        if(pomeloCheck.isSelected() && Integer.parseInt(this.naranjaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.LEVITE_POMELO), Integer.parseInt(this.naranjaSpinner.getValue().toString()));
        }

        if(manzanaCheck.isSelected() && Integer.parseInt(this.manzanaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.LEVITE_MANZANA), Integer.parseInt(this.manzanaSpinner.getValue().toString()));
        }

        if(limonadaCheck.isSelected() && Integer.parseInt(this.limonadaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.LEVITE_LIMONADA), Integer.parseInt(this.limonadaSpinner.getValue().toString()));
        }
        
        if(cepitaCheck.isSelected() && Integer.parseInt(this.cepitaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.CEPITA), Integer.parseInt(this.cepitaSpinner.getValue().toString()));
        }

        if(scheweppesPomeloCheck.isSelected() && Integer.parseInt(this.scheweppesPomeloSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.SCHEWEPPES_POMELO), Integer.parseInt(this.scheweppesPomeloSpinner.getValue().toString()));
        }

        if(scheweppesTonicaCheck.isSelected() && Integer.parseInt(this.scheweppesTonicaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.LEVITE_LIMONADA), Integer.parseInt(this.scheweppesTonicaSpinner.getValue().toString()));
        }        

        if(waterCheck.isSelected() && Integer.parseInt(this.waterSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.AGUA), Integer.parseInt(this.waterSpinner.getValue().toString()));
        }

        if(waterGasCheck.isSelected() && Integer.parseInt(this.waterGasSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.AGUA_GAS), Integer.parseInt(this.waterGasSpinner.getValue().toString()));
        }

        if(exprimidoCheck.isSelected() && Integer.parseInt(this.exprimidoSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.EXPRIMIDO), Integer.parseInt(this.exprimidoSpinner.getValue().toString()));
        }

        if(licuadoLecheCheck.isSelected() && Integer.parseInt(this.licuadoLecheSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.LICUADO_LECHE), Integer.parseInt(this.licuadoLecheSpinner.getValue().toString()));
        }

        if(licuadoAguaCheck.isSelected() && Integer.parseInt(this.licuadoAguaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.LICUADO_AGUA), Integer.parseInt(this.licuadoAguaSpinner.getValue().toString()));
        }

        if(limonadaCheck.isSelected() && Integer.parseInt(this.limonadaSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.LIMONADA), Integer.parseInt(this.limonadaSpinner.getValue().toString()));
        }

        if(shakeChocolateCheck.isSelected() && Integer.parseInt(this.shakeChocolateSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.MILK_SHAKE_CHOCO), Integer.parseInt(this.shakeChocolateSpinner.getValue().toString()));
        }

        if(shakeDulceLecheCheck.isSelected() && Integer.parseInt(this.shakeDulceLecheSpinner.getValue().toString()) > 0 ) {
            noAlcoholDrinks.put((NoAlcoholDrinksEnum.MILK_SHAKE_DULCE_LECHE), Integer.parseInt(this.shakeDulceLecheSpinner.getValue().toString()));
        }

        // nombra la mesa elegida
        this.selectedTable.getState();
        //this.tableOne.setBackground(Color.red);

        for (Map.Entry<NoAlcoholDrinksEnum, Integer> entry : noAlcoholDrinks.entrySet()) {
            //System.out.println("key --> " + entry.getKey());
            //System.out.println("value --> " + entry.getValue());

        }

        /*
        Otra forma de iterar el map
        noAlcoholDrinks.entrySet().stream().map((entry) -> {
            Object key = entry.getKey();
            return entry;
        }).forEachOrdered((entry) -> {
            Object value = entry.getValue();
        });
        */

        this.DrinkNoAlcoholFrame.dispatchEvent(new WindowEvent(this.DrinkNoAlcoholFrame, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_acceptNoAlcoholDrinksActionPerformed

    private void pomeloTorosCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomeloTorosCheckActionPerformed
        if(pomeloTorosCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.torosPomeloSpinner.setEnabled(true);
            this.torosPomeloSpinner.setModel(model);
        } else {
            this.torosPomeloSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_pomeloTorosCheckActionPerformed

    private void scheweppesPomeloCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheweppesPomeloCheckActionPerformed
        if(scheweppesPomeloCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.scheweppesPomeloSpinner.setEnabled(true);
            this.scheweppesPomeloSpinner.setModel(model);
        } else {
            this.scheweppesPomeloSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_scheweppesPomeloCheckActionPerformed

    private void limonadaElaboradoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limonadaElaboradoCheckActionPerformed
        if(limonadaElaboradoCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.limonada_elaborada_Spinner.setEnabled(true);
            this.limonada_elaborada_Spinner.setModel(model);
        } else {
            this.limonada_elaborada_Spinner.setEnabled(false);
        }
    }//GEN-LAST:event_limonadaElaboradoCheckActionPerformed

    private void licuadoLecheCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licuadoLecheCheckActionPerformed
        if(licuadoLecheCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.licuadoLecheSpinner.setEnabled(true);
            this.licuadoLecheSpinner.setModel(model);
        } else {
            this.licuadoLecheSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_licuadoLecheCheckActionPerformed

    private void licuadoAguaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licuadoAguaCheckActionPerformed
        if(licuadoAguaCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.licuadoAguaSpinner.setEnabled(true);
            this.licuadoAguaSpinner.setModel(model);
        } else {
            this.licuadoAguaSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_licuadoAguaCheckActionPerformed

    private void shakeChocolateCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shakeChocolateCheckActionPerformed
        if(shakeChocolateCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.shakeChocolateSpinner.setEnabled(true);
            this.shakeChocolateSpinner.setModel(model);
        } else {
            this.shakeChocolateSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_shakeChocolateCheckActionPerformed

    private void limonadaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limonadaCheckActionPerformed
        if(limonadaCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.limonadaSpinner.setEnabled(true);
            this.limonadaSpinner.setModel(model);
        } else {
            this.limonadaSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_limonadaCheckActionPerformed

    private void cepitaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepitaCheckActionPerformed
        if(cepitaCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.cepitaSpinner.setEnabled(true);
            this.cepitaSpinner.setModel(model);
        } else {
            this.cepitaSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_cepitaCheckActionPerformed

    private void waterCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterCheckActionPerformed
        if(waterCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.waterSpinner.setEnabled(true);
            this.waterSpinner.setModel(model);
        } else {
            this.waterSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_waterCheckActionPerformed

    private void waterGasCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterGasCheckActionPerformed
        if(waterGasCheck.isSelected()) {
            SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 50, 1);
            this.waterGasSpinner.setEnabled(true);
            this.waterGasSpinner.setModel(model);
        } else {
            this.waterGasSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_waterGasCheckActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        
        System.out.println("mesa elegida " + this.selectedTable.getState());
        
        System.out.println("Usuario mesa: " + this.tableUser.getNombre());
        
        for (Map.Entry<NoAlcoholDrinksEnum, Integer> entry : this.noAlcoholDrinks.entrySet()) {
            System.out.println("key --> " + entry.getKey());
            System.out.println("value --> " + entry.getValue());

        }
        
        // Guardar en la bbdd "la sesión" del usuario con todos los elementos 
        // de la mesa elegida
        // tener en cuenta los precios de los productos.
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        System.out.println("Start Vitto Project");
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VittoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VittoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VittoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VittoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("Start run vittoFrame");
                new VittoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame CandyProductsFrame;
    private javax.swing.JFrame DrinkAlcoholFrame;
    private javax.swing.JFrame DrinkNoAlcoholFrame;
    private javax.swing.JFrame SaladsProductFrame;
    private javax.swing.JButton SaveButton;
    private javax.swing.JFrame SelectOrder;
    private javax.swing.JFrame SuggestedPromosFrame;
    private javax.swing.JButton acceptNoAlcoholDrinks;
    private javax.swing.JButton cancelNoAlcoholDrinks;
    private javax.swing.JButton candyProducts;
    private javax.swing.JCheckBox cepitaCheck;
    private javax.swing.JSpinner cepitaSpinner;
    private javax.swing.JButton closeTable;
    private javax.swing.JCheckBox cocaColaCheck;
    private javax.swing.JCheckBox cocaLightCheck;
    private javax.swing.JSpinner cocaLightSpinner;
    private javax.swing.JSpinner cocaSpinner;
    private javax.swing.JButton consuming;
    private javax.swing.JButton deleteTable;
    private javax.swing.JButton drinkAlcohol;
    private javax.swing.JButton drinkNoAlcohol;
    private javax.swing.JComboBox<String> employeeNameCombo;
    private javax.swing.JCheckBox exprimidoCheck;
    private javax.swing.JSpinner exprimidoSpinner;
    private javax.swing.JCheckBox fantaCheck;
    private javax.swing.JSpinner fantaSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox licuadoAguaCheck;
    private javax.swing.JSpinner licuadoAguaSpinner;
    private javax.swing.JCheckBox licuadoLecheCheck;
    private javax.swing.JSpinner licuadoLecheSpinner;
    private javax.swing.JCheckBox limonadaCheck;
    private javax.swing.JCheckBox limonadaElaboradoCheck;
    private javax.swing.JSpinner limonadaSpinner;
    private javax.swing.JSpinner limonada_elaborada_Spinner;
    private javax.swing.JCheckBox manzanaCheck;
    private javax.swing.JSpinner manzanaSpinner;
    private javax.swing.JCheckBox naranjaCheck;
    private javax.swing.JSpinner naranjaSpinner;
    private javax.swing.JButton payAction;
    private javax.swing.JCheckBox pomeloCheck;
    private javax.swing.JSpinner pomeloSpinner;
    private javax.swing.JCheckBox pomeloTorosCheck;
    private javax.swing.JButton promotions;
    private javax.swing.JButton saladProducts;
    private javax.swing.JCheckBox scheweppesPomeloCheck;
    private javax.swing.JSpinner scheweppesPomeloSpinner;
    private javax.swing.JCheckBox scheweppesTonicaCheck;
    private javax.swing.JSpinner scheweppesTonicaSpinner;
    private javax.swing.JButton seeConsuming;
    private javax.swing.JCheckBox shakeChocolateCheck;
    private javax.swing.JSpinner shakeChocolateSpinner;
    private javax.swing.JCheckBox shakeDulceLecheCheck;
    private javax.swing.JSpinner shakeDulceLecheSpinner;
    private javax.swing.JCheckBox spriteCheck;
    private javax.swing.JSpinner spriteSpinner;
    private javax.swing.JCheckBox spriteZeroCheck;
    private javax.swing.JSpinner spriteZeroSpinner;
    private javax.swing.JButton tableFour;
    private javax.swing.JButton tableOne;
    private javax.swing.JButton tableThree;
    private javax.swing.JButton tableTwo;
    private javax.swing.JCheckBox tonicaCheck;
    private javax.swing.JSpinner torosPomeloSpinner;
    private javax.swing.JSpinner torosTonicaSpinner;
    private javax.swing.JCheckBox waterCheck;
    private javax.swing.JCheckBox waterGasCheck;
    private javax.swing.JSpinner waterGasSpinner;
    private javax.swing.JSpinner waterSpinner;
    // End of variables declaration//GEN-END:variables
}
